// src/components/DataAnalysis.vue
<template>
  <a-layout style="padding: 24px">
    <a-layout-content>
      <a-spin :spinning="loading">
        <a-row :gutter="[24, 24]">
          <a-col :span="6" v-for="(data, index) in analysisData" :key="index">
            <a-card>
              <a-statistic
                :title="data.title"
                :value="data.value"
                :value-style="{ color: data.color }"
              >
                <template #prefix>
                  <component :is="data.icon" style="font-size: 24px" />
                </template>
                <template #suffix>{{ data.prefix }}</template>
              </a-statistic>
            </a-card>
          </a-col>
        </a-row>

        <a-row :gutter="[16, 16]" style="margin-top: 24px">
          <a-col :span="12">
            <a-card title="学习进度分析">
              <div ref="chartRef1" style="height: 400px"></div>
            </a-card>
          </a-col>
          <a-col :span="12">
            <a-card title="学习时长分布">
              <div ref="chartRef2" style="height: 400px"></div>
            </a-card>
          </a-col>
        </a-row>
      </a-spin>
    </a-layout-content>
  </a-layout>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, nextTick } from 'vue';
import { message } from 'ant-design-vue';
import * as echarts from 'echarts';
import {
  UserOutlined,
  BookOutlined,
  CheckCircleOutlined,
  RiseOutlined,
} from '@ant-design/icons-vue';

const loading = ref(true);
const chartRef1 = ref<HTMLElement | null>(null);
const chartRef2 = ref<HTMLElement | null>(null);

const analysisData = reactive([
  {
    title: '学习能力评估',
    value: 0,
    icon: UserOutlined,
    prefix: '分',
    color: '#1890ff',
  },
  {
    title: '知识点掌握度',
    value: 0,
    icon: BookOutlined,
    prefix: '%',
    color: '#52c41a',
  },
  {
    title: '完成任务数',
    value: 0,
    icon: CheckCircleOutlined,
    prefix: '个',
    color: '#722ed1',
  },
  {
    title: '学习进度',
    value: 0,
    icon: RiseOutlined,
    prefix: '%',
    color: '#fa8c16',
  },
]);

const fetchAnalysisData = async () => {
  try {
    // 模拟API调用
    setTimeout(() => {
      // 更新分析数据
      analysisData[0].value = 85;
      analysisData[1].value = 78;
      analysisData[2].value = 12;
      analysisData[3].value = 65;

      loading.value = false;
      initCharts();
    }, 1000);
  } catch (error) {
    message.error('获取学情分析数据失败，请重试');
    console.error('获取分析数据错误:', error);
    loading.value = false;
  }
};

const initCharts = async () => {
  await nextTick();

  if (chartRef1.value) {
    const chart1 = echarts.init(chartRef1.value);
    chart1.setOption({
      title: {
        text: '知识点掌握情况',
      },
      tooltip: {},
      radar: {
        indicator: [
          { name: '语言知识', max: 100 },
          { name: '文学常识', max: 100 },
          { name: '阅读能力', max: 100 },
          { name: '写作能力', max: 100 },
          { name: '口语表达', max: 100 },
        ],
      },
      series: [
        {
          type: 'radar',
          data: [
            {
              value: [80, 75, 85, 70, 78],
              name: '班级平均水平',
            },
          ],
        },
      ],
    });
  }

  if (chartRef2.value) {
    const chart2 = echarts.init(chartRef2.value);
    chart2.setOption({
      title: {
        text: '每周学习时长分布',
      },
      xAxis: {
        type: 'category',
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
      },
      yAxis: {
        type: 'value',
      },
      series: [
        {
          data: [30, 35, 40, 38, 42, 25, 20],
          type: 'bar',
        },
      ],
    });
  }
};

onMounted(() => {
  fetchAnalysisData();
});
</script>

// src/components/DataAnalysis/index.tsx
import React, { useState, useEffect } from "react";
import { Layout, Card, Row, Col, Statistic, Spin, message } from "antd";
import {
  UserOutlined,
  BookOutlined,
  CheckCircleOutlined,
  RiseOutlined,
} from "@ant-design/icons";

const { Content } = Layout;

const DataAnalysis: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [analysisData, setAnalysisData] = useState([
    {
      title: "学习能力评估",
      value: 0,
      icon: <UserOutlined style={{ fontSize: "24px" }} />,
      prefix: "分",
      color: "#1890ff",
    },
    {
      title: "知识点掌握度",
      value: 0,
      icon: <BookOutlined style={{ fontSize: "24px" }} />,
      prefix: "%",
      color: "#52c41a",
    },
    {
      title: "完成任务数",
      value: 0,
      icon: <CheckCircleOutlined style={{ fontSize: "24px" }} />,
      prefix: "个",
      color: "#722ed1",
    },
    {
      title: "学习进度",
      value: 0,
      icon: <RiseOutlined style={{ fontSize: "24px" }} />,
      prefix: "%",
      color: "#fa8c16",
    },
  ]);

  useEffect(() => {
    fetchAnalysisData();
  }, []);

  const fetchAnalysisData = async () => {
    try {
      const response = await fetch("/api/ai/analysis-data");
      if (!response.ok) {
        throw new Error("获取分析数据失败");
      }
      const data = await response.json();
      setAnalysisData((prev) =>
        prev.map((item, index) => ({
          ...item,
          value: data[index].value,
        }))
      );
    } catch (error) {
      message.error("获取学情分析数据失败，请重试");
      console.error("获取分析数据错误:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout style={{ padding: "24px" }}>
      <Content>
        <Spin spinning={loading}>
          <Row gutter={[24, 24]}>
            {analysisData.map((data, index) => (
              <Col span={6} key={index}>
                <Card>
                  <Statistic
                    title={data.title}
                    value={data.value}
                    prefix={data.icon}
                    suffix={data.prefix}
                    valueStyle={{ color: data.color }}
                  />
                </Card>
              </Col>
            ))}
          </Row>
        </Spin>
      </Content>
    </Layout>
  );
};

export default DataAnalysis;
